import React, { useState } from 'react';
import { MODEL_OPTIONS, AVAILABLE_TOOLS, StackConfiguration } from '../../shared/types';

interface StackBuilderProps {
  onStackConfigured: (stack: StackConfiguration) => void;
}

export default function StackBuilder({ onStackConfigured }: StackBuilderProps) {
  // Default configuration
  const [selectedModel, setSelectedModel] = useState(MODEL_OPTIONS[1].id); // Default to mid-tier model
  const [temperature, setTemperature] = useState(0.7);
  const [maxTokens, setMaxTokens] = useState(1000);
  const [selectedTools, setSelectedTools] = useState<string[]>([]);
  const [architecture, setArchitecture] = useState('');
  const [isConfiguring, setIsConfiguring] = useState(true);
  const [error, setError] = useState('');

  // Find the selected model details
  const selectedModelDetails = MODEL_OPTIONS.find(model => model.id === selectedModel) || MODEL_OPTIONS[1];

  const handleTemperatureChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setTemperature(parseFloat(e.target.value));
  };

  const handleMaxTokensChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setMaxTokens(parseInt(e.target.value, 10));
  };

  const toggleToolSelection = (toolId: string) => {
    if (selectedTools.includes(toolId)) {
      setSelectedTools(selectedTools.filter(id => id !== toolId));
    } else {
      // Limit to 3 tools
      if (selectedTools.length < 3) {
        setSelectedTools([...selectedTools, toolId]);
      } else {
        setError('You can only select up to 3 tools. Please deselect one first.');
        setTimeout(() => setError(''), 3000);
      }
    }
  };

  const generateArchitecture = () => {
    // In a real implementation, this would be generated by the StackBuilder agent
    const buzzwords = [
      'distributed neural architecture',
      'edge-quantized synthetic data generation',
      'blockchain-secured inference pipeline',
      'quantum-inspired embedding matrix',
      'federated attention mechanism',
      'post-hoc explainability layer',
      'multi-modal vector retrieval system',
      'hyperdimensional computing substrate'
    ];

    // Pick 3 random buzzwords and combine them
    const randomBuzzwords = [];
    for (let i = 0; i < 3; i++) {
      const idx = Math.floor(Math.random() * buzzwords.length);
      randomBuzzwords.push(buzzwords[idx]);
      buzzwords.splice(idx, 1); // Remove to avoid duplicates
    }

    setArchitecture(`A cutting-edge ${randomBuzzwords[0]} with ${randomBuzzwords[1]} and ${randomBuzzwords[2]}.`);
  };

  const handleConfigureStack = () => {
    // Validate
    if (selectedTools.length === 0) {
      setError('Please select at least one tool.');
      return;
    }

    // Create stack configuration
    const stackConfig: StackConfiguration = {
      model_name: selectedModel,
      temperature: temperature,
      max_tokens: maxTokens,
      tools_selected: selectedTools,
      architecture_description: architecture || 'A standard generative AI architecture with prompt-based control.'
    };

    // Notify parent component
    onStackConfigured(stackConfig);
    setIsConfiguring(false);
  };

  const handleEditStack = () => {
    setIsConfiguring(true);
  };

  return (
    <div className="bg-indigo-900/40 rounded-xl p-6 shadow-xl mb-8">
      <h2 className="text-2xl font-bold mb-4 text-center text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-teal-400">
        {isConfiguring ? 'Configure Your Stack' : 'Your Tech Stack'}
      </h2>

      {error && (
        <div className="bg-red-500/20 border border-red-500 text-red-200 px-4 py-2 rounded mb-4">
          {error}
        </div>
      )}

      {isConfiguring ? (
        <>
          {/* Model Selection */}
          <div className="mb-6">
            <label className="block mb-2 font-medium">LLM Model</label>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
              {MODEL_OPTIONS.map((model) => (
                <div
                  key={model.id}
                  className={`border p-3 rounded-lg cursor-pointer transition-all duration-200 ${
                    selectedModel === model.id
                      ? 'bg-indigo-600 border-indigo-400'
                      : 'bg-black/30 border-indigo-800 hover:border-indigo-600'
                  }`}
                  onClick={() => setSelectedModel(model.id)}
                >
                  <div className="font-bold">{model.name}</div>
                  <div className="text-xs text-indigo-300 mt-1">{model.description}</div>
                  <div className="mt-2">
                    {model.costTier === 'low' && <span className="text-green-400">$</span>}
                    {model.costTier === 'medium' && <span className="text-yellow-400">$$</span>}
                    {model.costTier === 'high' && <span className="text-red-400">$$$</span>}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Temperature Slider */}
          <div className="mb-6">
            <label className="block mb-2 font-medium">
              Temperature: <span className="text-yellow-400">{temperature.toFixed(1)}</span>
            </label>
            <input
              type="range"
              min="0"
              max="2"
              step="0.1"
              value={temperature}
              onChange={handleTemperatureChange}
              className="w-full h-2 bg-indigo-800 rounded-lg appearance-none cursor-pointer"
            />
            <div className="flex justify-between text-xs text-indigo-400 mt-1">
              <span>Predictable (0.0)</span>
              <span>Balanced (1.0)</span>
              <span>Creative (2.0)</span>
            </div>
          </div>

          {/* Max Tokens Slider */}
          <div className="mb-6">
            <label className="block mb-2 font-medium">
              Max Tokens: <span className="text-yellow-400">{maxTokens}</span>
            </label>
            <input
              type="range"
              min="100"
              max={selectedModelDetails.maxTokens}
              step="100"
              value={maxTokens}
              onChange={handleMaxTokensChange}
              className="w-full h-2 bg-indigo-800 rounded-lg appearance-none cursor-pointer"
            />
            <div className="flex justify-between text-xs text-indigo-400 mt-1">
              <span>Brief</span>
              <span>Medium</span>
              <span>Verbose</span>
            </div>
          </div>

          {/* Tools Selection */}
          <div className="mb-6">
            <label className="block mb-2 font-medium">
              Select Tools <span className="text-indigo-400 text-sm">(Choose up to 3)</span>
            </label>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {AVAILABLE_TOOLS.map((tool) => (
                <div
                  key={tool.id}
                  className={`border p-3 rounded-lg cursor-pointer transition-all duration-200 ${
                    selectedTools.includes(tool.id)
                      ? 'bg-indigo-600 border-indigo-400'
                      : 'bg-black/30 border-indigo-800 hover:border-indigo-600'
                  }`}
                  onClick={() => toggleToolSelection(tool.id)}
                >
                  <div className="font-bold">{tool.name}</div>
                  <div className="text-xs text-indigo-300 mt-1">{tool.description}</div>
                </div>
              ))}
            </div>
          </div>

          {/* Architecture Description */}
          <div className="mb-6">
            <div className="flex justify-between items-center mb-2">
              <label className="font-medium">Architecture Description</label>
              <button
                onClick={generateArchitecture}
                className="text-xs bg-indigo-700 hover:bg-indigo-600 text-white py-1 px-2 rounded"
              >
                Generate Buzzwords
              </button>
            </div>
            <textarea
              placeholder="Describe your architecture (or let us generate it)"
              className="w-full bg-black/40 border border-indigo-800 p-3 rounded text-white h-24"
              value={architecture}
              onChange={(e) => setArchitecture(e.target.value)}
            />
          </div>

          {/* Submit Button */}
          <button
            onClick={handleConfigureStack}
            className="w-full bg-gradient-to-r from-blue-500 to-teal-500 hover:from-blue-600 hover:to-teal-600 text-white font-bold py-3 px-4 rounded transition-all duration-200"
          >
            Configure Tech Stack
          </button>
        </>
      ) : (
        <>
          {/* Stack Summary */}
          <div className="bg-black/30 p-4 rounded-lg mb-4">
            <div className="mb-3">
              <span className="text-indigo-400 font-medium">Model:</span>{' '}
              <span className="text-white">{MODEL_OPTIONS.find(model => model.id === selectedModel)?.name}</span>
            </div>
            <div className="mb-3">
              <span className="text-indigo-400 font-medium">Temperature:</span>{' '}
              <span className="text-white">{temperature.toFixed(1)}</span>
            </div>
            <div className="mb-3">
              <span className="text-indigo-400 font-medium">Max Tokens:</span>{' '}
              <span className="text-white">{maxTokens}</span>
            </div>
            <div className="mb-3">
              <span className="text-indigo-400 font-medium">Tools:</span>{' '}
              <div className="flex flex-wrap gap-2 mt-1">
                {selectedTools.map(toolId => (
                  <span key={toolId} className="bg-indigo-800 text-xs py-1 px-2 rounded">
                    {AVAILABLE_TOOLS.find(tool => tool.id === toolId)?.name}
                  </span>
                ))}
              </div>
            </div>
            <div>
              <span className="text-indigo-400 font-medium">Architecture:</span>{' '}
              <p className="text-white text-sm mt-1">{architecture || 'A standard generative AI architecture with prompt-based control.'}</p>
            </div>
          </div>

          {/* Edit Button */}
          <button
            onClick={handleEditStack}
            className="w-full bg-indigo-700 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded transition-all duration-200"
          >
            Edit Stack
          </button>
        </>
      )}
    </div>
  );
} 